on: [push]

jobs:
  dci_lint_job:
    runs-on: ubuntu-latest
    name: A job to run DCI Lint on DCI Lint
    steps:
    - name: Lint Git Repo
      id: lint-git-repo
      uses: petermetz/gh-action-dci-lint@v0.1.1
      with:
        lint-git-repo-request: '{"cloneUrl": "https://github.com/petermetz/dci-lint.git", "targetPhrasePatterns": [], "configDefaultsUrl": "https://inclusivenaming.org/json/dci-lint-config-recommended-v1.json" }'
    - name: Get the output response
      run: echo "${{ steps.lint-git-repo.outputs.lint-git-repo-response }}"
